hotel/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView

urlpatterns = patterns('',
    url(r'^$','hotel.views.index'),
    url(r'^(?P<reservation_id>\d+)/$','hotel.views.reservation'),
    url(r'^rooms/$','hotel.views.rooms'),
    url(r'^new/$','hotel.views.newres'),
    url(r'^new/(?P<room_id>\d+)/$','hotel.views.newres_room'),
    url(r'^rooms/(?P<room_id>\d+)/$','hotel.views.oneroom'),
    url(r'^newcust/$','hotel.views.newcust'),
    url(r'^editcust/(?P<id_cust>\d+)/$','hotel.views.editcust'),
    url(r'^editcust/$','hotel.views.rooms'),
    url(r'^oneroom/$','hotel.views.oneroom'),
)

simpleportal/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^', include('hotel.urls')),
    url(r'^hotel/', include('hotel.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

hotel/models.py
from django.db import models
import datetime
from datetime import date
import calendar
from django.utils import timezone 

# Constants
CUSTOMER_TYPE = (
    ('SIR','Senior'),
    ('DIS','Disabled'),
    ('FAM','Family'),
    ('YOU','Young'))

PRODUCT_TYPE = (
    ('SER','Service'),
    ('FOO','Food'),
    ('DRI','Drink'),
    ('OTH','Other'))

STATUSES = (
    ('RES','Reserved'),
    ('CIN','Checked in'),
    ('COU','Checked out'),
    ('CLO','Closed'))

FREE_ROOM = "Free Room"
EMPTY = "Empty"

'''
PHYSICAL PARTS OF HOTEL
'''
# Hotel ROOMS
class Room(models.Model):
    number = models.IntegerField()
    position = models.CharField(max_length=200,null=True, blank=True)
    description = models.TextField()
    beds = models.IntegerField()
    fridge = models.IntegerField()
    tresor = models.IntegerField()
    disabledppl = models.BooleanField()
    balcony = models.IntegerField()
    accessories = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    appartment = models.BooleanField()
    
    def __unicode__(self):
        return str(self.number)
    def get_text(self):
        return str(self.number)
    def get_floor(self):
        return str(self.number/100)

    #LIST OF ALL ROOMS
    @staticmethod
    def list_rooms():
        allrooms = Room.objects.all().order_by('number')
        thelist = []
        for r in allrooms:
            thelist.append((str(r.number),str(r.number)))
        return thelist


    # GET CHECKED IN RESERVATION
    def resact(self):
        resall = Reservation.objects.filter(room=self).order_by('created').reverse()
        for res in resall:
            if res.status == "CIN":
                return res
        return None
    
    # IS THE ROOM OCCUPIED
    def is_occupied(self):
        if self.resact():
            return True
        return False

    # THE ROOM IS OCCUPIED --- OVERDUE
    def is_overdue(self):
        res = self.resact()
        now = timezone.now()
        if res:
            if res.reserved_until < now:
                return True
            return False
        return False

    # IS LAST DAY OCCUPIED
    def is_last_day(self):
        res = self.resact()
        now = timezone.now()
        if res:
            if not self.is_overdue():
                if res.reserved_until.date() == now.date():
                    return True
                return False
            return False
        return False

    # GET THE CUSTOMER
    def res_name(self):
        res = self.resact()
        if res:
            return res.customer
        if self.is_reserved():
            return self.get_reserved().customer
        return str(FREE_ROOM)
    
    # GET STATUS OF RESERVATION
    def restat(self):
        res = self.resact()
        if res:
            return res.get_status()
        if self.is_reserved():
            return self.get_reserved().get_status()
        return str(EMPTY)

    # GET RESERVATION DAYS
    def period_from(self):
        res = self.resact()
        if res:
            return res.reserved_from
        if self.is_reserved():
            return self.get_reserved().reserved_from
        return str("")
    def period_until(self):
        res = self.resact()
        if res:
            return res.reserved_until
        if self.is_reserved():
            return self.get_reserved().reserved_until
        return str("")

    # IF THE ROOM WAS RESERVED BUT NOT CHECKED IN
    def get_reserved(self):
        resall = Reservation.objects.filter(room=self).order_by('created').reverse()
        now = timezone.now()
        if not self.is_occupied():
            for res in resall:
                if res.status == "RES":
                    if now.date() >= res.reserved_from.date() and now.date() < res.reserved_until.date():
                        return res
        return None

    def is_reserved(self):
        res = self.get_reserved()
        if res:
            return True
        return False
        
    #get ALL RESERVATIONS
    def allres(self):
        return Reservation.objects.filter(room=self).order_by('created')







        
#Parking spaces
class ParkingSpace(models.Model):
    position = models.CharField(max_length=200)
    in_garage = models.BooleanField()
    description = models.TextField(null=True, blank=True)

#Products and services that are sold in the hotel
class Product(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    unit = models.CharField(max_length=200,null=True, blank=True)
    size = models.DecimalField(max_digits=10,decimal_places=2,null=True, blank=True)
    stock = models.DecimalField(max_digits=10,decimal_places=2,null=True, blank=True)
    prod_type = models.CharField(max_length=20,choices=PRODUCT_TYPE)

'''
RESERVATION TABLES
'''
# Customers
class Customer(models.Model):
    registered = models.DateTimeField()
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    address = models.TextField()
    town = models.CharField(max_length=200)
    state = models.CharField(max_length=200,null=True, blank=True)
    country = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=200)
    passnumber = models.CharField(max_length=200)
    bank = models.CharField(max_length=200,null=True,blank=True)
    account = models.CharField(max_length=200,null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    cust_type = models.CharField(max_length=20,choices=CUSTOMER_TYPE)
    def __unicode__(self):
        return self.surname + ", " + self.name 
    def get_text(self):
        return self.surname + ", " + self.name
    def get_type(self):
        for index, item in enumerate(CUSTOMER_TYPE):
            if item[0] == self.cust_type:
                return item[1]
    
    #LIST OF ALL CUSTOMERS
    @staticmethod
    def list_customers():
        allcust = Customer.objects.all().order_by('surname')
        thelist = []
        a = 0
        for r in allcust:
            thelist.append((a,str(r.surname + ", " + r.name)))
            a = a+1
        return thelist

#Reservations
class Reservation(models.Model):
    customer = models.ForeignKey(Customer)
    room = models.ForeignKey(Room)
    all_inclusive = models.BooleanField()
    created = models.DateTimeField()
    reserved_from = models.DateTimeField(null=True, blank=True)
    reserved_until = models.DateTimeField(null=True, blank=True)
    checkin = models.DateTimeField(null=True, blank=True)
    checkout = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20,choices=STATUSES)
    def get_status(self):
        for index, item in enumerate(STATUSES):
            if item[0] == self.status:
                return item[1]
    def get_formated_date_from(self):
        return self.reserved_from.strftime("%d.%m.%Y")
    def get_formated_date_until(self):
        return self.reserved_until.strftime("%d.%m.%Y")


#Reservation items
class ReservationItem(models.Model):
    reservation = models.ForeignKey(Reservation)
    product = models.ForeignKey(Product)
    quantity = models.DecimalField(max_digits=10,decimal_places=2,null=True, blank=True)
    delivered_to_room = models.BooleanField()
    details = models.TextField()

#separate table for parking multiple cars
class ParkingItem(models.Model):
    reservation = models.ForeignKey(Reservation)
    space = models.ForeignKey(ParkingSpace)

hotel/forms.py
from django import forms
from hotel.models import Reservation, Room, Customer, STATUSES, CUSTOMER_TYPE
from django.forms import ModelForm
from django.contrib.admin import widgets 

# NOW DO THE MODEL FORM


class NewResForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

class NewCustForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

hotel/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import Context, loader
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from hotel.models import Reservation, Room
from django.utils import timezone
from django.shortcuts import redirect
import random
from django.http import Http404
from hotel.forms import NewResForm, NewCustForm, RoomForm
from hotel.models import Customer
#from django.views.generic.simple import direct_to_template
#from django.views.generic import TemplateView

'''
INDEX
'''
def index(request):
    res_list = Reservation.objects.all().order_by('created').reverse()
    c = RequestContext(request, {'res_list': res_list})
    return render_to_response('hotel/Index.html', c)

'''
ROOMS
'''
def rooms(request):
    room_list = Room.objects.all().order_by('number')
    res_list = Reservation.objects.all().order_by('created')
    c = RequestContext(request, {'room_list': room_list,'res_list': res_list})
    return render_to_response('hotel/Rooms.html', c)
    

'''
OPEN ONE ROOM
'''
def oneroom(request, room_id):
    instance = get_object_or_404(Room, number=room_id)
    form = RoomForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/hotel/rooms/')
    return render(request, 'hotel/Room.html', {'form': form})

'''
RESERVATION
'''
def reservation(request, reservation_id):
    instance = get_object_or_404(Reservation, id=reservation_id)
    form = NewResForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/hotel/rooms/')
    return render(request, 'hotel/NewRes.html', {'form': form})


'''
NEW RESERVATION
'''
def newres(request): 
    if request.method == 'POST':
        form = NewResForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/hotel/rooms/')
    else:
        form = NewResForm(initial={'created': timezone.now() })
    return render(request, 'hotel/NewRes.html', {'form': form})


def newres_room(request, room_id):
    try:
        p = Room.objects.get(number=room_id)
    except Room.DoesNotExist:
        raise Http404
    
    if request.method == 'POST':
        form = NewResForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/hotel/rooms/')
    else:
        form = NewResForm(initial={'created': timezone.now() })
    return render(request, 'hotel/NewRes.html', {'form': form,'room': p,})


'''
NEW CUSTOMER
'''

def newcust(request):
    if request.method == 'POST':
        form = NewCustForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/hotel/rooms/')
    else:
        form = NewCustForm(initial={'registered': timezone.now() })
    return render(request, 'hotel/NewCust.html', {'form': form})


'''
EDIT CUSTOMER
'''

def editcust(request,id_cust):
    instance = get_object_or_404(Customer, id=id_cust)
    form = NewCustForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/hotel/rooms/')
    return render(request, 'hotel/NewCust.html', {'form': form})

hotel/templates/hotel/Index.html
{% include "hotel/header.html" %}


{% if res_list %}
    <table cellspacing='0' width="100%" title="Hotel Reservations" class="sortable winter">
    <thead>    
    <tr>
        <th>Room number</th>
        <th>Customer</th>
        <th>Created</th>
        <th>Reserved from</th>
        <th>Reserved until</th>
        <th>Check In</th>
        <th>Check Out</th>
        <th>Status</th>
        <th>All Inclusive</th>
    </tr>
    </thead>
    <tbody>
    {% for res in res_list %}
    <tr onClick="window.location.href='/hotel/{{ res.id }}'">
        <td>{{ res.room }}</td>
        <td>{{ res.customer }}</td>
        <td>{{ res.created }}</td>
        <td>{{ res.reserved_from }}</td>
        <td>{{ res.reserved_until }}</td>
        <td>{{ res.checkin }}</td>
        <td>{{ res.checkout }}</td>
        <td>{{ res.get_status }}</td>
        <td>{{ res.all_inclusive }}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>No Reservations found.</p>
{% endif %}

hotel/templates/hotel/NewCust.html
{% include "hotel/header.html" %}

<table cellspacing='0' width="100%" title="Hotel Reservation" class="winter">
    <thead>    
    <tr>
        <th>CUSTOMER DETAILS</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
        <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td><input type="submit" value="Save" /></td><td></td></tr>
        </form>
    </tbody>
</table>

hotel/templates/hotel/NewRes.html
{% include "hotel/header.html" %}

<!-- START OF TIMEPICKER HEAD -->
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.16/jquery-ui.min.js"></script>
<link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.16/themes/hot-sneaks/jquery-ui.css" />
<script src="/static/jquery-ui-timepicker-addon.js"></script>

<style>
/* css for timepicker */
.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
.ui-timepicker-div dl { text-align: left; }
.ui-timepicker-div dl dt { height: 25px; margin-bottom: -25px; }
.ui-timepicker-div dl dd { margin: 0 10px 10px 65px; }
.ui-timepicker-div td { font-size: 90%; }
.ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }
</style>
<!-- END OF TIMEPICKER HEAD -->


{% if room %}
<script type="text/javascript">
    window.onload = function(){
        var selObj = document.getElementById('id_room');
        var v = '{{ room.number }}';
        for ( var i = 0; i < selObj.options.length; i++ ) {
            if ( selObj.options[i].text == v ) {
                selObj.options[i].selected = true;
                return;
            }
        }
    }
</script>
{% endif %}

<br/ >
<table cellspacing='0' width="100%" title="Hotel Reservation" class="winter">
    <thead>    
    <tr>
        <th>RESERVATION DETAILS</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
        <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td><input type="submit" value="Save" /></td><td></td></tr>
        </form>
    </tbody>
</table>


<!-- TIMEPICKER INIT -->
<script>
$(document).ready(function() {
    $('#id_created').datetimepicker({ dateFormat: 'yy-mm-dd' });
    $('#id_checkin').datetimepicker({ dateFormat: 'yy-mm-dd' });
    $('#id_checkout').datetimepicker({ dateFormat: 'yy-mm-dd' });
    $('#id_reserved_until').datetimepicker({ dateFormat: 'yy-mm-dd' });
    $('#id_reserved_from').datetimepicker({ dateFormat: 'yy-mm-dd' });
});
</script>
<!-- END OF TIMEPICKER INIT -->

hotel/templates/hotel/Room.html
{% include "hotel/header.html" %}

<table cellspacing='0' width="100%" title="Hotel Reservation" class="winter">
    <thead>    
    <tr>
        <th>ROOM DETAILS</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
        <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td><input type="submit" value="Save" /></td><td></td></tr>
        </form>
    </tbody>
</table>
<a href="javascript:history.back(-1);"><< Go back</a></td>

hotel/templates/hotel/Rooms.html
{% include "hotel/header.html" %}

{% if room_list %}

<br/>
<table width="100%" class="gant">
<script>
var today = new Date();
var days = new Date(today.getFullYear(), today.getMonth()+1, 0).getDate();
document.write("<b>Current date: " + today + "</b>");

//create calendar
document.write("<tr>");
for(var k = 0; k<=days; k++)
{
    if(k ==0)
    {
        document.write("<td bgcolor='ffcc00'>ROOM</td>");
    }
    else
    {
        var tempDate = new Date(today.getFullYear(), today.getMonth(), k);
        var dateString = tempDate.getDate() + "." + (tempDate.getMonth()+1);
        
        if(k<10)
        {
            dateString = "0" + dateString;
        }
        
        if(tempDate.getDate() == today.getDate())
        {
            dateString = "<b>" + dateString + "</b>";
            document.write("<td bgcolor='FFFFBE'>" + dateString + "</td>");
        }
        else
        {
            if(tempDate.getDay() == 0 || tempDate.getDay() == 6)
            {
                document.write("<td bgcolor='DCF0F7'>" + dateString + "</td>");
            }
            else
            {
                document.write("<td>" + dateString + "</td>");
            }
        }
    }
}
document.write("</tr>");

</script>
{% for room in room_list %}
    <script>
        var dates = new Array();
        var l = 0;
    </script>
    
    {% for res in room.allres %}
        <script>
            dates[l] = '{{res.get_formated_date_from }}';
            l++;
            dates[l] = '{{res.get_formated_date_until }}';
            l++;
        </script>
    {% endfor%}

    <script>
    //create calendar
    document.write("<tr>");
    
    var reservedDay = false;
    
    for(var k = 0; k<=days; k++)
    {
        if(k ==0)
        {
            document.write("<td bgcolor='ffcc00'><a href='/hotel/rooms/{{ room.number }}'>" + '{{ room.number }}' + "</a></td>");
        }
        else 
        {
            var tempDate = new Date(today.getFullYear(), today.getMonth(), k);
            var dateString = tempDate.getDate() + "." + (tempDate.getMonth()+1);
            if(k<10)
            {
                dateString = "0" + dateString;
            }
            
            dateString += "." + today.getFullYear();
            
            
            
            if(dates.indexOf(dateString) > -1 )
            {
                if(dates.indexOf(dateString)%2==0)
                {
                    document.write("<td bgcolor='#336699'></td>");
                    reservedDay = true;
                }
                else
                {
                    document.write("<td bgcolor='#336699'></td>");
                    reservedDay = false;
                }
            }
            
            else if(reservedDay)
            {
                document.write("<td bgcolor='#336699'></td>");
            }
            else
            {
                if(tempDate.getDay() == 0 || tempDate.getDay() == 6)
                {
                    document.write("<td bgcolor='DCF0F7'>&nbsp;</td>");
                }
                else
                {
                    document.write("<td>&nbsp;</td>");
                }
            }
        }
    }
    document.write("</tr>");
    </script>

{% endfor %}
</table>

{% else %}
    <p>No rooms found.</p>
{% endif %}

hotel/templates/hotel/header.html
<!DOCTYPE html>
<LINK href="/static/main.css" rel="stylesheet" type="text/css" />
<link href="/static/jsgantt.css" rel="stylesheet" type="text/css" />
<script src="/static/sorttable.js"></script>
<script src="/static/jsgantt.js"></script>

<span class="headlink" onclick="window.location.href='/hotel/rooms/'">HOTELSYSTEM</span>

<div id='topmenu'>
<a href="/hotel/rooms">Room overview</a>
<a href="/hotel/">Reservations</a>
<a href="/hotel/new/">New Reservation</a>
<a href="/hotel/newcust/">New Customer</a>
</div>